workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

variables:
  TF_ROOT: ${CI_PROJECT_DIR}/terraform
  TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${CI_PROJECT_NAME}
  TF_HTTP_USERNAME: "gitlab-ci-token"
  TF_HTTP_PASSWORD: ${CI_JOB_TOKEN}
  TF_HTTP_ADDRESS: ${TF_ADDRESS}
  TF_HTTP_LOCK_ADDRESS: ${TF_ADDRESS}/lock
  TF_HTTP_UNLOCK_ADDRESS: ${TF_ADDRESS}/lock
  TF_HTTP_LOCK_METHOD: "POST"
  TF_HTTP_UNLOCK_METHOD: "DELETE"
  TF_HTTP_RETRY_WAIT_MIN: 5
  TF_PLUGIN_CACHE_DIR: "$CI_PROJECT_DIR/.terraform.d/plugin-cache"

cache:
  key:
    files:
      - terraform/.terraform.lock.hcl
  paths:
    - terraform/.terraform
    - .terraform.d/plugin-cache/

stages:
  - validate
  - plan
  - deploy
  # - ansible_deploy
  - cleanup

.terraform_base:
  image:
    name: hashicorp/terraform:1.14
    entrypoint: [""]
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: sts.amazonaws.com  # Must match the "Audience" in your AWS OIDC Provider
  before_script:
    - mkdir -p $TF_PLUGIN_CACHE_DIR
    - cd ${TF_ROOT}
    - terraform --version
    - terraform init -input=false
    - mkdir -p ~/.aws
    # Convert the environment variable token into a file
    - echo "${GITLAB_OIDC_TOKEN}" > /tmp/web_identity_token
    # with the env variable AWS_ROLE_ARN and AWS_WEB_IDENTITY_TOKEN_FILE, the AWS Provider for Terraform automatically calls AssumeRoleWithWebIdentity (via AWS STS)
    - export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/web_identity_token

validate:
  extends: .terraform_base
  stage: validate
  script:
    - terraform validate
    - terraform fmt

plan:
  extends: .terraform_base
  stage: plan
  script:
    - terraform plan -out=tfplan -input=false
  artifacts:
    paths:
      - ${TF_ROOT}/tfplan      

deploy:
  extends: .terraform_base
  stage: deploy
  script:
    - terraform apply -input=false -auto-approve tfplan
    
    # - echo "INSTANCE_IP=$(terraform output -raw ec2_public_ip)" >> ${CI_PROJECT_DIR}/ansible.env
    - echo "DB_ENDPOINT=$(terraform output -raw aurora_cluster_endpoint)" >> ${CI_PROJECT_DIR}/ansible.env
    - echo "SECRET_ARN=$(terraform output -raw aurora_secret_arn)" >> ${CI_PROJECT_DIR}/ansible.env
  artifacts:
    reports:
      dotenv: ansible.env
  when: manual

.ansible_deploy:
  stage: ansible_deploy
  image: python:3.11
  needs:
    - deploy
  before_script:
    - pip install ansible

    # Set up SSH permissions securely
    # Ensures the SSH config directory exists, -p avoids errors if it already exists
    - mkdir -p ~/.ssh
    # Required by SSH for security, Only the owner can read/write/execute
    - chmod 700 ~/.ssh
    # Copies your injected CI variable into a file
    - cp $EC2_SSH_PRIVATE_KEY ~/.ssh/id_rsa
    # SSH will refuse to use the key if permissions are too open, Only owner can read/write
    - chmod 600 ~/.ssh/id_rsa
    # Starts an SSH agent process, Allows keys to be loaded into memory instead of referencing files directly
    - eval $(ssh-agent -s)
    # Loads your private key into the agent, From this point, SSH (and Ansible) can use it automatically
    - ssh-add ~/.ssh/id_rsa
    # Disable strict host key checking for dynamic IP automation
    # Prevents prompts like: Are you sure you want to continue connecting (yes/no)?
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    # Run the playbook, passing the dynamic IP as the inventory and passing the variables
    - ansible-playbook -i "$INSTANCE_IP," -u ec2-user ${CI_PROJECT_DIR}/ansible/deploy-keycloak.yml --extra-vars "db_endpoint=$DB_ENDPOINT secret_arn=$SECRET_ARN"

cleanup:
  extends: .terraform_base
  stage: cleanup
  script:
    - terraform destroy -auto-approve
  when: manual
