workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - when: never

variables:
  TF_ROOT: ${CI_PROJECT_DIR}/terraform
  TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${CI_PROJECT_NAME}
  TF_HTTP_USERNAME: "gitlab-ci-token"
  TF_HTTP_PASSWORD: ${CI_JOB_TOKEN}
  TF_HTTP_ADDRESS: ${TF_ADDRESS}
  TF_HTTP_LOCK_ADDRESS: ${TF_ADDRESS}/lock
  TF_HTTP_UNLOCK_ADDRESS: ${TF_ADDRESS}/lock
  TF_HTTP_LOCK_METHOD: "POST"
  TF_HTTP_UNLOCK_METHOD: "DELETE"
  TF_HTTP_RETRY_WAIT_MIN: 5

cache:
  key: terraform-cache-${CI_COMMIT_REF_SLUG}
  paths:
    - ${TF_ROOT}/.terraform

stages:
  - validate
  - plan
  - deploy
  - ansible_deploy
  - cleanup

.terraform_base:
  image:
    name: hashicorp/terraform:1.14
    entrypoint: [""]
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: sts.amazonaws.com  # Must match the "Audience" in your AWS OIDC Provider
  before_script:
    - cd ${TF_ROOT}
    - terraform --version
    - terraform init -input=false
    - mkdir -p ~/.aws
    # Convert the environment variable token into a file
    - echo "${GITLAB_OIDC_TOKEN}" > /tmp/web_identity_token
    # with the env variable AWS_ROLE_ARN and AWS_WEB_IDENTITY_TOKEN_FILE, the AWS Provider for Terraform automatically calls AssumeRoleWithWebIdentity (via AWS STS)
    - export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/web_identity_token

validate:
  extends: .terraform_base
  stage: validate
  script:
    - terraform validate
    - terraform fmt

plan:
  extends: .terraform_base
  stage: plan
  script:
    - terraform plan -out=tfplan -input=false
  artifacts:
    paths:
      - ${TF_ROOT}/tfplan      

deploy:
  extends: .terraform_base
  stage: deploy
  script:
    - terraform apply -input=false -auto-approve tfplan
    # Extract outputs to files for the Ansible stage
    - terraform output -raw ec2_public_ip > ../instance_ip.txt
    - terraform output -raw aurora_cluster_endpoint > ../db_endpoint.txt
    - terraform output -raw aurora_secret_arn > ../secret_arn.txt
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/instance_ip.txt
      - ${CI_PROJECT_DIR}/db_endpoint.txt
      - ${CI_PROJECT_DIR}/secret_arn.txt
  when: manual

ansible_deploy:
  stage: ansible_deploy
  image: python:3.11
  needs:
    - deploy
  before_script:
    - pip install ansible

    # Set up SSH permissions securely
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cp $EC2_SSH_PRIVATE_KEY ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_rsa
    # Disable strict host key checking for dynamic IP automation
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    # Read the Terraform outputs into variables
    - export INSTANCE_IP=$(cat ${CI_PROJECT_DIR}/instance_ip.txt)
    - export DB_ENDPOINT=$(cat ${CI_PROJECT_DIR}/db_endpoint.txt)
    - export SECRET_ARN=$(cat ${CI_PROJECT_DIR}/secret_arn.txt)
    
    # Run the playbook, passing the dynamic IP as the inventory and passing the variables
    - ansible-playbook -i "$INSTANCE_IP," -u ec2-user ${CI_PROJECT_DIR}/ansible/deploy-keycloak.yml --extra-vars "db_endpoint=$DB_ENDPOINT secret_arn=$SECRET_ARN"

cleanup:
  extends: .terraform_base
  stage: cleanup
  script:
    - terraform destroy -auto-approve
  when: manual
