workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - when: never

image:
  name: hashicorp/terraform:1.14
  entrypoint: [""]
variables:
  TF_ROOT: ${CI_PROJECT_DIR}/terraform
  TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${CI_PROJECT_NAME}
  TF_HTTP_USERNAME: "gitlab-ci-token"
  TF_HTTP_PASSWORD: ${CI_JOB_TOKEN}
  TF_HTTP_ADDRESS: ${TF_ADDRESS}
  TF_HTTP_LOCK_ADDRESS: ${TF_ADDRESS}/lock
  TF_HTTP_UNLOCK_ADDRESS: ${TF_ADDRESS}/lock
  TF_HTTP_LOCK_METHOD: "POST"
  TF_HTTP_UNLOCK_METHOD: "DELETE"
  TF_HTTP_RETRY_WAIT_MIN: 5
  AWS_ROLE_ARN: "arn:aws:iam::542776678091:oidc-provider/gitlab.com"

cache:
  key: terraform-cache-${CI_COMMIT_REF_SLUG}
  paths:
    - ${TF_ROOT}/.terraform

before_script:
  - cd ${TF_ROOT}
  - terraform --version
  - terraform init -input=false

stages:
  - validate
  - plan
  - deploy
  - cleanup

validate:
  stage: validate
  script:
    - terraform validate
    - terraform fmt

plan:
  stage: plan
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: sts.amazonaws.com  # Must match the "Audience" in your AWS OIDC Provider
  script:
    - mkdir -p ~/.aws
    # Convert the environment variable token into a file
    - echo "${GITLAB_OIDC_TOKEN}" > /tmp/web_identity_token
    - export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/web_identity_token  
    - terraform plan -out=tfplan -input=false
  artifacts:
    paths:
      - ${TF_ROOT}/tfplan      

deploy:
  stage: deploy
  script:
    - terraform apply -input=false -auto-approve tfplan
  when: manual

cleanup:
  stage: cleanup
  script:
    - terraform destroy -auto-approve
  when: manual
